server:
  port: 8001

spring:
  application:
    name: short-link-project
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: chen2020...
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: 5330c0340920d01c22b4ceddd5dc096b
  goto-domain:
    white-list:
      enable: true
      names: '知乎,掘金,博客园,CSDN,个人博客'
      details:
        - zhihu.com
        - juejin.cn
        - cnblogs.com
        - csdn.net
        - blog.axinstar.top

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
